spring.application.name=FamilyHelpUAE
spring.datasource.url =jdbc:mysql://localhost:3306/familyhelpuaedb?useSSL=false&serverTimezone=UTC
spring.datasource.username = group7@CSC408
spring.datasource.password = group7@CSC408
spring.jpa.hibernate.ddl-auto=update

# Enable debug logging for Spring Security to diagnose 403 issues
logging.level.org.springframework.security=DEBUG


# tls settings for https
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=group7@CSC408
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=serverkeys
server.ssl.enabled=true